# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: webspoon-*
  pull_request:
    branches: webspoon-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2  # tycho-packaging-plugin
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "webspoon/nightly"
        prerelease: false
        title: "Auto-build of ${{ github.ref }} by GitHub Actions."
        files: |
          bundles/org.eclipse.rap.rwt/target/org.eclipse.rap.rwt-*.jar
          bundles/org.eclipse.rap.jface/target/org.eclipse.rap.jface-*.jar
          bundles/org.eclipse.rap.fileupload/target/org.eclipse.rap.fileupload-*.jar
          bundles/org.eclipse.rap.filedialog/target/org.eclipse.rap.filedialog-*.jar
          tests/org.eclipse.rap.rwt.testfixture/target/org.eclipse.rap.rwt.testfixture-*.jar

